# Generated by Django 4.1.3 on 2022-11-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
